version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - pipeline-network
    volumes:
      - redis-data:/data

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: events_db
    ports:
      - "3306:3306"
    networks:
      - pipeline-network
    volumes:
      - mysql-data:/var/lib/mysql

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    environment:
      - REDIS_HOST=redis
      - MYSQL_HOST=mysql
      - SCRAPER_INTERVAL=300
    networks:
      - pipeline-network
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - REDIS_HOST=redis
      - MYSQL_HOST=mysql
      - WORKER_INTERVAL=60
    networks:
      - pipeline-network
    depends_on:
      - redis
      - mysql

networks:
  pipeline-network:
    driver: bridge

volumes:
  redis-data:
  mysql-data:
